swarm:
  agents: # supported: manager, analyst, googler, crunchbase_searcher
    - type: manager
      n: 2
    - type: analyst
      n: 2
    - type: googler
      n: 2
    - type: crunchbase_searcher # scraper can only have one job in parallel
      n: 1
  timeout_min: 10
  run_dir: ./tmp/swarm
task:
  role: |
    Senior analyst in the venture capital firm, who has a proven track record of consistently funding successful startups.
  global_goal: |
    A new startup just send us their pitch. Find if the startup is worth investing in. The startup is called Upgrade and it is in the  online credit cards field in US.
  goals:
    - Research the field and identify the main problems and challenges, creating an extensive list of potential obstacles that can impact the field's growth or a company's success. Use trusted sources such as Crunchbase, TechCrunch, Venturebeat,
      CB Insights to gather information.
    - Create a technology description for a non-tech audience using easy-to-understand language and providing links to the main articles in the field. Use trusted sources such as Crunchbase, TechCrunch, Venturebeat,
      CB Insights to gather information.
    - Research actual market size, growth rate, and trends for the field, providing links to trusted sources such as Google, CB Insights, Crunchbase, Techcrunch, Techmeme and Venturebeat.
    - Compile a list of the top 5 articles and top 5 Twitter threads in the field for last year, including the article or thread title, source with link, and date of publication. Use trusted sources such as TechCrunch and Twitter to gather information.
    - Identify top 10 companies backed by VCs in the world and sort descending by total amount of raised funding, providing their key description, HQ locations, total amount raised, website visits for last month, visits growth for last month, and Crunchbase profile links. Use trusted sources such as Crunchbase, TechCrunch and SimilarWeb to gather information.
    - Identify the top investors in the field and provide specific details on their investments, such as "company AAA (link) invested in company BBB (link) $XX in year YYYY". Use trusted sources such as Crunchbase, TechCrunch, Venturebeat,
      CB Insights to gather information.
    - List the top 5 M&A deals in the field for last 5 years, including the company website, key description, HQ country, transaction date, and price. Use trusted sources such as crunchbase, techcrunch, techmeme, venturebeat, CB Insights to gather information.
    - Identify the top 5 public companies in the field listed more than 5 years ago and separate list of  top 5 public companies in the field listed less than 5 years ago, including their names, HQ country, market cap, sales growth, EV/Sales LTM multiples, and Yahoo Finance profile links. Use trusted sources such as Yahoo Finance to gather information.
